In [2]:
a=1

In [3]:
a

1

In [4]:
a=1; b=2

In [5]:
a

1

In [6]:
a
b

2

In [9]:
print(a)
print(b)

1
2


1

In [11]:
type(a)

int

In [17]:
a = 1.1

In [18]:
type(a)

float

In [19]:
a

1.1

In [20]:
int(a)

1

In [21]:
float(int(a))

1.0

In [22]:
int(float(int(a)))

1

In [23]:
a=1; a = float(a); print(type(a))

<class 'float'>


In [24]:
a=1.2; a=int(a); print(type(a))

<class 'int'>


In [25]:
a='123'

In [26]:
a

'123'

In [27]:
type(a)

str

In [29]:
a='abc'

In [31]:
a[0]

'a'

In [32]:
a[1]

'b'

In [33]:
a[2]

'c'

In [34]:
a[-1]

'c'

In [35]:
a = '123'

In [36]:
a = [1,2,3]

In [37]:
a

[1, 2, 3]

In [38]:
type(a)

list

In [40]:
a = [1,2,'ab',[4,5]]

In [41]:
a[0]

1

In [43]:
a[-1]

[4, 5]

In [44]:
a[-1][0]

4

In [45]:
a = '123'; a=list(a)

In [46]:
a

['1', '2', '3']

In [47]:
a = [1,'2',[3,'4']]; print(type(a))

<class 'list'>


In [48]:
a = {"a":"apple", "b":"banana", "c" : 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [49]:
a["c"]

2014

In [52]:
a["a"]

'apple'

In [1]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [5]:
import numpy as np #data science에서 numpy가 진짜 많이 쓰인다
b = np.array(a)
print(b)
print(type(b)) #ndarray : n-dimensional array

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [3]:
print(b*b)
#행렬 곱하기 할 수 없는데,, 이걸 그냥 행렬과 비슷한 것이라고 생각하고 행렬은 아님!

[[ 1  4  9]
 [ 9 64  0]]


In [9]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [10]:
c*c.T 
#.T Transpose(numpy에 있음)
#그래서 행렬 계산한 값이 나오게 된다

matrix([[14, 19],
        [19, 73]])

In [11]:
s = 'abcdef'

In [12]:
type(s)

str

In [13]:
print(type(s))

<class 'str'>
